# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83e30f64703265f3ac8010c381454076a127be9264eae4b4df134a6410655a82f36a56fa8df87ddcf102d3b38a04935627a41905eca6f161e8a8a559e90587c8

test:
  secret_key_base: 49e5c6c86618589356d59d98391b0fc1c542623f403720c77401010691166557aa13f01bd9d2bba8385f9d51cdb591c44c16117340317b1c126bc75b17436009

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
